# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-24 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0004_auto_20181024_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountParse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='число обходов')),
                ('name', models.CharField(max_length=128, verbose_name='имя парсера')),
            ],
        ),
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('url', models.URLField(max_length=500, verbose_name='адрес парсинга')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 10, 24, 7, 7, 21, 10075, tzinfo=utc), verbose_name='Время для архива')),
                ('show', models.BooleanField(default=True)),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
        migrations.CreateModel(
            name='TypePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='тип')),
                ('type_sighn', models.CharField(default='', max_length=64)),
                ('description', models.TextField(verbose_name='Описание типа')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 10, 24, 7, 7, 21, 10075, tzinfo=utc), verbose_name='Время для архива типов')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='parsing',
            name='type_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TypePage'),
        ),
    ]
