# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-05 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181024_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 18, 12, 3, 483867, tzinfo=utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 18, 12, 3, 483867, tzinfo=utc), verbose_name='Время для архива типов'),
        ),
    ]
