# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-04 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190304_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 19, 56, 53, 574038, tzinfo=utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 19, 56, 53, 574038, tzinfo=utc), verbose_name='Время для архива типов'),
        ),
    ]
