# Generated by Django 3.0 on 2021-04-23 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210423_1751'),
        ('base', '0006_auto_20190304_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=68, null=True, verbose_name='наименование')),
                ('description', models.TextField(blank=True, max_length=128, null=True, verbose_name='описание')),
                ('keywords', models.TextField(blank=True, max_length=128, null=True, verbose_name='ключевые слова')),
                ('h1', models.TextField(blank=True, max_length=68, null=True, verbose_name='h1')),
            ],
        ),
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 17, 51, 44, 207731, tzinfo=utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Article'),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='type_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.TypePage'),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 17, 51, 44, 207731, tzinfo=utc), verbose_name='Время для архива типов'),
        ),
    ]
