# Generated by Django 3.0 on 2021-04-23 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_auto_20210423_2031'),
        ('base', '0007_auto_20210423_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seo',
        ),
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 20, 31, 55, 437830, tzinfo=utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 20, 31, 55, 437830, tzinfo=utc), verbose_name='Время для архива типов'),
        ),
    ]
