# Generated by Django 3.0 on 2021-04-27 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210423_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 20, 44, 40, 211597, tzinfo=utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 20, 44, 40, 211597, tzinfo=utc), verbose_name='Время для архива типов'),
        ),
    ]
