# Generated by Django 4.2.2 on 2023-07-02 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_parsing_created_alter_typepage_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 16, 4, 23, 586788, tzinfo=datetime.timezone.utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 16, 4, 23, 586559, tzinfo=datetime.timezone.utc), verbose_name='Время для архива типов'),
        ),
    ]
