# Generated by Django 4.2.3 on 2023-07-04 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_parsing_created_alter_typepage_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 9, 31, 3, 653268, tzinfo=datetime.timezone.utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 9, 31, 3, 653030, tzinfo=datetime.timezone.utc), verbose_name='Время для архива типов'),
        ),
    ]
