# Generated by Django 4.2.3 on 2023-07-25 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_parsing_created_alter_typepage_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsing',
            name='news',
        ),
        migrations.AddField(
            model_name='parsing',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='html для парсинга'),
        ),
        migrations.AddField(
            model_name='parsing',
            name='site_sighn',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 19, 37, 32, 833099, tzinfo=datetime.timezone.utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True, verbose_name='адрес парсинга'),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 19, 37, 32, 832857, tzinfo=datetime.timezone.utc), verbose_name='Время для архива типов'),
        ),
    ]
