# Generated by Django 4.2.3 on 2023-07-27 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_parsing_news_parsing_html_parsing_site_sighn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsing',
            name='parsing_for_choices',
            field=models.CharField(choices=[('okt_avito_from_admin', 'Парсинг авито для октябрьского из админки'), ('default', 'Невыбрано')], default='default', max_length=30, verbose_name='от куда и для чего парсим'),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 18, 53, 32, 162794, tzinfo=datetime.timezone.utc), verbose_name='Время для архива'),
        ),
        migrations.AlterField(
            model_name='parsing',
            name='site_sighn',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='typepage',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 18, 53, 32, 162555, tzinfo=datetime.timezone.utc), verbose_name='Время для архива типов'),
        ),
    ]
