# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='порядок в списке'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Slug организации'),
        ),
    ]
