# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20170311_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='menu_level',
            field=models.BooleanField(default=False, verbose_name='Верхний уровень'),
        ),
    ]
