# Generated by Django 3.0 on 2021-04-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210423_1751'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0014_auto_20210423_1751'),
        ('organisations', '0007_auto_20180508_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organisations.Organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='place',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='place.Place', verbose_name='Местро расположения'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_organisation', to='article.Article', verbose_name='Привязанная статья'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_organisation', to='organisations.Organisation', verbose_name='Фотография к статье'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_organisation', to=settings.AUTH_USER_MODEL),
        ),
    ]
