# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
