# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170117_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.ImageField(blank=True, null=True, upload_to='enumeration', verbose_name='image_book'),
        ),
    ]
