# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import meta.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0006_auto_20161223_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ф.И.О или название')),
                ('slug', models.CharField(blank=True, default='slug', max_length=128, null=True, verbose_name='Slug имени')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('type_enumeration', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип книги')),
                ('show', models.BooleanField(default=False, verbose_name='Отображать на сайте')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='номер перечисления')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок размещения в днях')),
                ('image_enumeration', models.ImageField(blank=True, null=True, upload_to='enumeration', verbose_name='image_enumeration')),
                ('seo_title', models.CharField(blank=True, max_length=160, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='enumeration.Enumeration')),
                ('place', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_enumerate', to='place.Place', verbose_name='Местро расположения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
    ]
