# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enumeration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumeration',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главная страница'),
        ),
    ]
