# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enumeration', '0002_enumeration_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumeration',
            name='menu_level',
            field=models.BooleanField(default=False, verbose_name='Верхний уровень'),
        ),
    ]
