# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='Название статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article', verbose_name='Article')),
                ('show', models.BooleanField(default=False, verbose_name='Отображать на сайте')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата размещения')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коментарии к фотографии')),
                ('category', models.CharField(blank=True, choices=[('news', 'Новости'), ('activity', 'Мероприятия'), ('nature', 'Природа')], max_length=3, null=True, verbose_name='тип статьи')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
