# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20161223_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('new', 'Новости'), ('act', 'Мероприятия'), ('nat', 'Природа'), ('vid', 'Видео')], max_length=3, null=True, verbose_name='тип статьи'),
        ),
    ]
