# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20181105_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chronology_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Хронологическая дата'),
        ),
    ]
