# Generated by Django 3.0 on 2021-04-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('article', '0008_auto_20210423_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='site_sighn',
        ),
        migrations.AddField(
            model_name='article',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Seo'),
        ),
    ]
