# Generated by Django 4.2.2 on 2023-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20210423_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='site_sighn',
            field=models.CharField(default='volgograd', max_length=256, verbose_name='название сайта'),
            preserve_default=False,
        ),
    ]
