# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название населенного пункта')),
                ('type_place', models.CharField(max_length=128, verbose_name='Тип населенного пункта')),
                ('show', models.BooleanField(default=False, verbose_name='Отображать на сайте')),
                ('first_order', models.BooleanField(default=False, verbose_name='Первые в списке')),
                ('description', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2016, 8, 31, 8, 52, 29, 193577), verbose_name='Срок размещения в днях')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='place.Place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='place.Place', verbose_name='Группа'),
        ),
    ]
