# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_description',
            field=models.ImageField(blank=True, null=True, upload_to='media/description', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 31, 12, 20, 53, 177491), verbose_name='Срок размещения в днях'),
        ),
    ]
