# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0002_auto_20160831_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='коментарии к фотографии'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Название фотографии'),
        ),
        migrations.AddField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата размещения'),
        ),
        migrations.AddField(
            model_name='photo',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Отображать на сайте'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', upload_to='media', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='place.Place', verbose_name='Местро расположения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_description',
            field=models.ImageField(blank=True, null=True, upload_to='/description', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок размещения в днях'),
        ),
    ]
