# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20160915_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', upload_to='description', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_description',
            field=models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Image'),
        ),
    ]
