# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_place_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('nature', 'Природа'), ('soc', 'Общество'), ('info', 'Информация')], default='', max_length=128, verbose_name='Тип фотографии'),
        ),
    ]
