# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-09 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_auto_20170509_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('', '------'), ('nature', 'Природа'), ('soc', 'Общество'), ('info', 'Информация')], max_length=128, null=True, verbose_name='Тип фотографии'),
        ),
    ]
