# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_auto_20170509_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Название фотографии'),
        ),
    ]
