# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_auto_20170609_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='place.Place', verbose_name='Местро расположения'),
        ),
    ]
