# Generated by Django 3.0 on 2021-04-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210423_1751'),
        ('base', '0007_auto_20210423_1751'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0013_auto_20170622_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='seo_title',
        ),
        migrations.AddField(
            model_name='place',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Seo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='article.Article', verbose_name='Привязанная статья'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo', to='place.Place', verbose_name='Местро расположения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='place.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
